name: Mirror Jellyfin JSON Plugins

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  download-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download JSON file
        run: curl -o manifest-stable.json https://blr1.mirror.jellyfin.org/files/plugin/manifest-stable.json

      - name: Commit and push changes
        run: |
          git config --local user.email "alirezajavdan142@yahoo.com"
          git config --local user.name "BlackCharon142"
          git add manifest-stable.json
          git commit -m "Update manifest-stable.json" || echo "No changes to commit"
          git push
